//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasPorCobrar
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BALANCE
    {
        [Browsable(false)]
        [DisplayName ("ID cliente")]
        public int ID_cliente { get; set; }
        [DisplayName("ID cliente")]
        public System.DateTime Fecha_corte { get; set; }
        public decimal Monto { get; set; }
        [DisplayName("ID balance")]
        public int ID_balance { get; set; }

        
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
