//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasPorCobrar
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public CLIENTE()
        {

            this.BALANCE = new HashSet<BALANCE>();
            this.TRANSACCION = new HashSet<TRANSACCION>();
        }

        [DisplayName("ID cliente")]
        public int ID_cliente { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        [DisplayName("Limite crédito")]
        public decimal Limite_credito { get; set; }
        public bool Estado { get; set; }

        [Browsable(false)]
        public virtual ICollection<BALANCE> BALANCE { get; set; }
        [Browsable(false)]
        public virtual ICollection<TRANSACCION> TRANSACCION { get; set; }
        public override string ToString()
        {
            return Nombre;
        }
    }
}
