//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasPorCobrar
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION
    {
        public int ID_transaccion { get; set; }
        public string Tipo_movimiento { get; set; }
        public int ID_documento { get; set; }
        public int Num_documento { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ID_cliente { get; set; }
        public decimal Monto { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }

		
	}
}
