//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasPorCobrar
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class USUARIOS
    {
        public int ID_usuario { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public string Estado { get; set; }
        public int ID_rol { get; set; }

        [Browsable(false)]
        public virtual ROLES ROLES { get; set; }
    }
}
